### ISSUE TITLE
structopt::StructOpt  is not satisfied by clap_verbosity_flag::Verbosity

### ISSUE THREAD

**Issue by drazisil** [rust-cli/clap-verbosity-flag#36]
I'm having the following issue when trying to use `clap-verbosity-flag`

## Errors
```
the trait bound `clap_verbosity_flag::Verbosity: structopt::StructOpt` is not satisfied

the trait `structopt::StructOpt` is not implemented for `clap_verbosity_flag::Verbosity`rustc(E0277)
main.rs(18, 17): the trait `structopt::StructOpt` is not implemented for `clap_verbosity_flag::Verbosity`
the trait bound `clap_verbosity_flag::Verbosity: structopt::StructOptInternal` is not satisfied

the trait `structopt::StructOptInternal` is not implemented for `clap_verbosity_flag::Verbosity`rustc(E0277)
```

## Versions:
* `clap-verbosity-flag = "1.0.0"`
* `structopt = "0.3.26"`
* rustc 1.60.0 (7737e0b5c 2022-04-04)

## Code to reproduce

```rust
use structopt::StructOpt;

#[derive(StructOpt)]
struct Cli {
    #[structopt(flatten)]
    verbosity: clap_verbosity_flag::Verbosity,
}
```

Guidance would be appreciated. :pray:

**Comment by epage** [comment]
[structopt was merged into clap 3.0 and is no longer actively maintained](https://docs.rs/structopt/latest/structopt/#maintenance).  See the [clap 3.0 changelog](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#300---2021-12-31) for a migration guide.

As of [clap-verbosity-flag 0.4](https://github.com/rust-cli/clap-verbosity-flag/blob/master/CHANGELOG.md#040---2021-12-31), it is built on clap instead of structopt
